name: webinar
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.11
  - pip=23.2.1
  - python=3.11.5
  - readline=8.2
  - setuptools=68.0.0
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2023c
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - attrs==23.1.0
      - certifi==2023.7.22
      - charset-normalizer==3.2.0
      - exceptiongroup==1.1.3
      - h11==0.14.0
      - idna==3.4
      - outcome==1.2.0
      - packaging==23.1
      - pysocks==1.7.1
      - python-dotenv==1.0.0
      - requests==2.31.0
      - selenium==4.13.0
      - sniffio==1.3.0
      - sortedcontainers==2.4.0
      - tqdm==4.66.1
      - trio==0.22.2
      - trio-websocket==0.10.4
      - urllib3==2.0.5
      - webdriver-manager==4.0.1
      - wsproto==1.2.0
